# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pizza.ui'
#
# Created: Thu Feb 20 03:28:35 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtGui.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 10, 801, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.name_input = QtGui.QLineEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(274, 51, 261, 31))
        self.name_input.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.name_input.setMaxLength(32773)
        self.name_input.setObjectName("name_input")
        self.ingredients_label = QtGui.QLabel(self.centralwidget)
        self.ingredients_label.setGeometry(QtCore.QRect(10, 100, 791, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.ingredients_label.setFont(font)
        self.ingredients_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ingredients_label.setObjectName("ingredients_label")
        self.order_btn = QtGui.QPushButton(self.centralwidget)
        self.order_btn.setEnabled(False)
        self.order_btn.setGeometry(QtCore.QRect(674, 546, 101, 31))
        self.order_btn.setObjectName("order_btn")
        self.pizza_contents = QtGui.QLabel(self.centralwidget)
        self.pizza_contents.setGeometry(QtCore.QRect(40, 440, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pizza_contents.setFont(font)
        self.pizza_contents.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pizza_contents.setWordWrap(True)
        self.pizza_contents.setObjectName("pizza_contents")
        self.price_label = QtGui.QLabel(self.centralwidget)
        self.price_label.setGeometry(QtCore.QRect(40, 520, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.price_label.setFont(font)
        self.price_label.setObjectName("price_label")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 140, 781, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(150, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cheese_label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.cheese_label.setFont(font)
        self.cheese_label.setObjectName("cheese_label")
        self.horizontalLayout.addWidget(self.cheese_label)
        self.meat_label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.meat_label.setFont(font)
        self.meat_label.setObjectName("meat_label")
        self.horizontalLayout.addWidget(self.meat_label)
        self.vegetables_label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vegetables_label.setFont(font)
        self.vegetables_label.setObjectName("vegetables_label")
        self.horizontalLayout.addWidget(self.vegetables_label)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(360, 190, 112, 126))
        self.widget1.setObjectName("widget1")
        self.meat_group = QtGui.QVBoxLayout(self.widget1)
        self.meat_group.setContentsMargins(0, 0, 0, 0)
        self.meat_group.setObjectName("meat_group")
        self.ch_bacon = QtGui.QCheckBox(self.widget1)
        self.ch_bacon.setObjectName("ch_bacon")
        self.meat_group.addWidget(self.ch_bacon)
        self.ch_prosciutto = QtGui.QCheckBox(self.widget1)
        self.ch_prosciutto.setObjectName("ch_prosciutto")
        self.meat_group.addWidget(self.ch_prosciutto)
        self.ch_salami = QtGui.QCheckBox(self.widget1)
        self.ch_salami.setObjectName("ch_salami")
        self.meat_group.addWidget(self.ch_salami)
        self.ch_chicken_breast = QtGui.QCheckBox(self.widget1)
        self.ch_chicken_breast.setObjectName("ch_chicken_breast")
        self.meat_group.addWidget(self.ch_chicken_breast)
        self.ch_ham = QtGui.QCheckBox(self.widget1)
        self.ch_ham.setObjectName("ch_ham")
        self.meat_group.addWidget(self.ch_ham)
        self.widget2 = QtGui.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(570, 190, 149, 256))
        self.widget2.setObjectName("widget2")
        self.vegetables_group = QtGui.QVBoxLayout(self.widget2)
        self.vegetables_group.setContentsMargins(0, 0, 0, 0)
        self.vegetables_group.setObjectName("vegetables_group")
        self.ch_fresh_mushrooms = QtGui.QCheckBox(self.widget2)
        self.ch_fresh_mushrooms.setObjectName("ch_fresh_mushrooms")
        self.vegetables_group.addWidget(self.ch_fresh_mushrooms)
        self.ch_smoked_mushrooms = QtGui.QCheckBox(self.widget2)
        self.ch_smoked_mushrooms.setObjectName("ch_smoked_mushrooms")
        self.vegetables_group.addWidget(self.ch_smoked_mushrooms)
        self.ch_red_onion = QtGui.QCheckBox(self.widget2)
        self.ch_red_onion.setObjectName("ch_red_onion")
        self.vegetables_group.addWidget(self.ch_red_onion)
        self.ch_tomatoes = QtGui.QCheckBox(self.widget2)
        self.ch_tomatoes.setObjectName("ch_tomatoes")
        self.vegetables_group.addWidget(self.ch_tomatoes)
        self.ch_garlic = QtGui.QCheckBox(self.widget2)
        self.ch_garlic.setObjectName("ch_garlic")
        self.vegetables_group.addWidget(self.ch_garlic)
        self.ch_rucola = QtGui.QCheckBox(self.widget2)
        self.ch_rucola.setObjectName("ch_rucola")
        self.vegetables_group.addWidget(self.ch_rucola)
        self.ch_marinated_gogoshars = QtGui.QCheckBox(self.widget2)
        self.ch_marinated_gogoshars.setObjectName("ch_marinated_gogoshars")
        self.vegetables_group.addWidget(self.ch_marinated_gogoshars)
        self.ch_corn = QtGui.QCheckBox(self.widget2)
        self.ch_corn.setObjectName("ch_corn")
        self.vegetables_group.addWidget(self.ch_corn)
        self.ch_parsley = QtGui.QCheckBox(self.widget2)
        self.ch_parsley.setObjectName("ch_parsley")
        self.vegetables_group.addWidget(self.ch_parsley)
        self.ch_chili_pepper = QtGui.QCheckBox(self.widget2)
        self.ch_chili_pepper.setObjectName("ch_chili_pepper")
        self.vegetables_group.addWidget(self.ch_chili_pepper)
        self.widget3 = QtGui.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(140, 190, 87, 152))
        self.widget3.setObjectName("widget3")
        self.cheese_group = QtGui.QVBoxLayout(self.widget3)
        self.cheese_group.setContentsMargins(0, 0, 0, 0)
        self.cheese_group.setObjectName("cheese_group")
        self.ch_feta = QtGui.QCheckBox(self.widget3)
        self.ch_feta.setObjectName("ch_feta")
        self.cheese_group.addWidget(self.ch_feta)
        self.ch_parmesan = QtGui.QCheckBox(self.widget3)
        self.ch_parmesan.setObjectName("ch_parmesan")
        self.cheese_group.addWidget(self.ch_parmesan)
        self.ch_mozarella = QtGui.QCheckBox(self.widget3)
        self.ch_mozarella.setObjectName("ch_mozarella")
        self.cheese_group.addWidget(self.ch_mozarella)
        self.ch_dor_blue = QtGui.QCheckBox(self.widget3)
        self.ch_dor_blue.setObjectName("ch_dor_blue")
        self.cheese_group.addWidget(self.ch_dor_blue)
        self.ch_edam = QtGui.QCheckBox(self.widget3)
        self.ch_edam.setObjectName("ch_edam")
        self.cheese_group.addWidget(self.ch_edam)
        self.ch_branza = QtGui.QCheckBox(self.widget3)
        self.ch_branza.setObjectName("ch_branza")
        self.cheese_group.addWidget(self.ch_branza)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("MainWindow", "Pizza Adriano", None, QtGui.QApplication.UnicodeUTF8))
        self.name_input.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Please enter your name", None, QtGui.QApplication.UnicodeUTF8))
        self.ingredients_label.setText(QtGui.QApplication.translate("MainWindow", "Choose pizza ingredients", None, QtGui.QApplication.UnicodeUTF8))
        self.order_btn.setText(QtGui.QApplication.translate("MainWindow", "Order", None, QtGui.QApplication.UnicodeUTF8))
        self.pizza_contents.setText(QtGui.QApplication.translate("MainWindow", "Your pizza contains:", None, QtGui.QApplication.UnicodeUTF8))
        self.price_label.setText(QtGui.QApplication.translate("MainWindow", "Price: 00 lei", None, QtGui.QApplication.UnicodeUTF8))
        self.cheese_label.setText(QtGui.QApplication.translate("MainWindow", "Cheese", None, QtGui.QApplication.UnicodeUTF8))
        self.meat_label.setText(QtGui.QApplication.translate("MainWindow", "Meat", None, QtGui.QApplication.UnicodeUTF8))
        self.vegetables_label.setText(QtGui.QApplication.translate("MainWindow", "Vegetables", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_bacon.setText(QtGui.QApplication.translate("MainWindow", "Bacon", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_prosciutto.setText(QtGui.QApplication.translate("MainWindow", "Prosciutto", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_salami.setText(QtGui.QApplication.translate("MainWindow", "Salami", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_chicken_breast.setText(QtGui.QApplication.translate("MainWindow", "Chicken Breast", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_ham.setText(QtGui.QApplication.translate("MainWindow", "Ham", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_fresh_mushrooms.setText(QtGui.QApplication.translate("MainWindow", "Fresh mushrooms", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_smoked_mushrooms.setText(QtGui.QApplication.translate("MainWindow", "Smoked mushrooms", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_red_onion.setText(QtGui.QApplication.translate("MainWindow", "Red onion", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_tomatoes.setText(QtGui.QApplication.translate("MainWindow", "Tomatoes", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_garlic.setText(QtGui.QApplication.translate("MainWindow", "Garlic", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_rucola.setText(QtGui.QApplication.translate("MainWindow", "Rucola", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_marinated_gogoshars.setText(QtGui.QApplication.translate("MainWindow", "Marinated Gogoshars", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_corn.setText(QtGui.QApplication.translate("MainWindow", "Corn", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_parsley.setText(QtGui.QApplication.translate("MainWindow", "Parsley", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_chili_pepper.setText(QtGui.QApplication.translate("MainWindow", "Chili pepper", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_feta.setText(QtGui.QApplication.translate("MainWindow", "Feta", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_parmesan.setText(QtGui.QApplication.translate("MainWindow", "Parmesan", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_mozarella.setText(QtGui.QApplication.translate("MainWindow", "Mozarella", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_dor_blue.setText(QtGui.QApplication.translate("MainWindow", "Dor Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_edam.setText(QtGui.QApplication.translate("MainWindow", "Edam", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_branza.setText(QtGui.QApplication.translate("MainWindow", "Branza", None, QtGui.QApplication.UnicodeUTF8))

